$ErrorActionPreference = "Stop"
$paths = @(
  "src/components/home",
  "src/components/forum",
  "src/components/external",
  "src/components/comparison",
  "src/components/ads",
  "src/components/templates",
  "src/components/admin/CategoryFAQEditor.tsx",
  "src/components/admin/CategoryFooterLinksEditor.tsx",
  "src/components/admin/CategoryLegalLinksEditor.tsx",
  "src/components/admin/HomeFAQEditor.tsx",
  "src/components/admin/ProjectCheckboxList.tsx",
  "src/components/AffiliateDisclaimer.tsx",
  "src/components/SocialLinks.tsx",
  "src/components/StarRatingWidget.tsx",
  "src/components/layout/MascotWidget.tsx",
  "src/components/layout/__tests__",
  "src/pages/About.tsx",
  "src/pages/AboutOrCategoryDetail.tsx",
  "src/pages/Categories.tsx",
  "src/pages/CategoryDetail.tsx",
  "src/pages/Forum.tsx",
  "src/pages/ForumThread.tsx",
  "src/pages/GoRedirect.tsx",
  "src/pages/HowWeCompare.tsx",
  "src/pages/TopApps.tsx",
  "src/pages/Welcome.tsx",
  "src/pages/admin/About.tsx",
  "src/pages/admin/Apps.tsx",
  "src/pages/admin/Categories.tsx",
  "src/pages/admin/FooterLinks.tsx",
  "src/pages/admin/Forum.tsx",
  "src/pages/admin/MultiPublisher.tsx",
  "src/pages/admin/Projects.tsx",
  "src/pages/admin/Redirects.tsx",
  "src/hooks/useBlogPosts.ts",
  "src/hooks/useCategories.ts",
  "src/hooks/useCategoryProjects.ts",
  "src/hooks/useDashboardTheme.ts",
  "src/hooks/useForceSEO.ts",
  "src/hooks/useForum.ts",
  "src/hooks/useGenerateCategoryContent.ts",
  "src/hooks/useGenerateCityContent.ts",
  "src/hooks/useGlobalAnalytics.ts",
  "src/hooks/useGlobalSearch.ts",
  "src/hooks/useLegalFooterLinks.ts",
  "src/hooks/usePopularFooterLinks.ts",
  "src/hooks/useProjects.ts",
  "src/hooks/usePromotedApps.ts",
  "src/hooks/useRedirects.ts",
  "src/hooks/useSEO.tsx",
  "src/hooks/useSeoRedirects.ts",
  "src/hooks/useTrackView.ts",
  "src/lib/__tests__",
  "src/lib/aboutContent.ts",
  "src/lib/countries.ts",
  "src/lib/legalCopy.ts",
  "src/lib/prerender.ts",
  "src/lib/seo.ts",
  "src/lib/storageImage.ts",
  "src/lib/tiertarifHomeContent.ts",
  "src/lib/tiertarifLinks.ts",
  "public/big-threes",
  "public/logos",
  "public/llms.txt",
  "supabase/functions/generate-city-content",
  "supabase/functions/generate-sitemap",
  "supabase/functions/go-redirect",
  "supabase/functions/google-ping",
  "supabase/functions/newsletter-subscribe",
  "supabase/functions/page-pulse",
  "supabase/functions/publish-external-page",
  "supabase/functions/tiertarif-ai",
  "supabase/functions/github-pulse",
  "supabase/functions/_shared",
  "MrMoneyWidget.tsx",
  "README_Tiertarif_Tests.md",
  "cleanup_manifest.md",
  "MIGRATION_LOG.md",
  "paket_b_manifest.md",
  "fix_tiertarif_asset_paths.sql",
  "set_tiertarif_theme.sql",
  "tiertarif_db.sql",
  "apply_package_a_cleanup.sh",
  "CHANGELOG.md"
)

foreach ($path in $paths) {
  if (Test-Path $path) {
    Remove-Item -Path $path -Recurse -Force
    Write-Host "Deleted $path"
  }
}

if (Test-Path "supabase/migrations") {
  Get-ChildItem "supabase/migrations" -Filter "*.sql" | Where-Object { $_.Name -ne "20260617103000_pv_launch_database_rls.sql" } | Remove-Item -Force
}

Write-Host "Phase 2 obsolete files cleanup completed."
